import React from 'react';

const Home = props => (
  <div className="home">
	<div className="intro">
		<h1>Welcome to Adam's Adventures</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum mattis gravida condimentum. Donec in tincidunt felis. Sed euismod diam a placerat placerat. Aliquam erat volutpat. Integer at tellus dolor. Vivamus accumsan ornare mi nec sodales. Vestibulum vel luctus dolor. Phasellus tempor justo lacus, at mattis purus convallis quis. Nunc sapien ex, laoreet id libero venenatis, scelerisque hendrerit ex. Sed vitae neque at tortor consectetur venenatis. Proin sodales leo non est ornare, ac placerat lectus venenatis. Nulla volutpat nibh nibh, at posuere ex efficitur eget. Donec eget diam sed magna sodales auctor.</p>
		<p>Sed ac scelerisque justo. Nunc ullamcorper, dolor in hendrerit ornare, turpis dui viverra felis, vitae accumsan lacus nisl vel lacus. Curabitur tincidunt varius ligula eget elementum. Duis at mauris quis dolor tempor molestie. Suspendisse potenti. Mauris eget nibh lorem. Sed nec justo placerat ipsum ornare fermentum. Ut scelerisque sem quis metus porttitor, quis pellentesque sapien ornare. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer tempus, massa a faucibus malesuada, eros quam iaculis massa, at blandit sapien magna ac risus. Nulla volutpat pellentesque nulla id gravida. Suspendisse aliquet libero nec rhoncus hendrerit.</p>
		<p>Cras posuere, tortor sed aliquam maximus, eros neque rhoncus lacus, a commodo massa lacus interdum tortor. Nam ac est nec diam consectetur gravida. Morbi magna risus, interdum eu eros id, pulvinar lacinia eros. Phasellus sed enim eu turpis egestas luctus. Nunc vel aliquam enim. Sed tristique varius lobortis. In vulputate arcu vestibulum, ultricies diam vel, euismod tortor. Nulla pulvinar tortor ut quam rutrum, nec tempus enim lacinia. Sed porttitor sed tortor vitae auctor. Duis nulla risus, tempor eu consectetur sed, sagittis id nulla. Proin sed imperdiet sem. Morbi ut eros eu lacus hendrerit posuere.</p>
		<p>Morbi ac massa dolor. Donec faucibus dui at orci luctus, vitae semper lorem pulvinar. Vestibulum nec nisl vel nisi aliquet volutpat. In bibendum eros non lorem facilisis, eu dapibus neque sagittis. Mauris et erat luctus, rutrum lacus a, interdum sapien. Nam commodo sed augue eget commodo. Nunc dapibus augue ex, ac viverra leo dapibus vitae. Sed ultrices quam eget nibh commodo malesuada. Phasellus id est sed nunc gravida sodales in non sem. Nam consectetur efficitur feugiat. Ut et consectetur massa. Mauris ac fermentum est, ut efficitur ex.</p>
		<p>Aenean imperdiet ante lectus, vel pharetra turpis consectetur eu. Phasellus varius est vel mollis rhoncus. Etiam et tempor felis. Vestibulum volutpat magna lacus, in pulvinar ipsum placerat sed. Aenean vel luctus nibh, in pretium elit. In nec posuere nulla. Nullam eget arcu eget tellus tempus elementum id ut quam. Fusce pharetra ultricies lacinia. Curabitur pretium, lorem id pharetra interdum, arcu erat molestie odio, et dapibus lorem velit at quam. Ut molestie orci non ultrices tempus. Mauris tempor odio neque, non dictum diam faucibus quis. Sed vestibulum nunc maximus justo ultricies, vitae condimentum enim lobortis. Sed fringilla metus sit amet mollis pellentesque. Suspendisse maximus elit vitae velit porta malesuada.</p>
	</div>
  </div>
);

export default Home;
